export const Babydatas = [
    
    {
        "id":"B1",
        "name":"Milky Soft Face Cream With Murumuru Butter for Babies, 60 ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/_/m/_milky_soft_face_cream_.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Moisturizes | Soothes | Heals Chapped Skin",
        "rating":4.9,
        "reviews":217,
        "price":"199",
        "sellerTag":"BEST SELLER",
        "category":"Lotion",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


     },
     {
        "id":"B2",
        "name":"Moisturizing Bathing Bar Soap For Babies, pack of 2*75g",
        "pImg":"https://honasa-mamaearth-production.imgix.net/f/d/fds_9573-props_qwhqvlzshodrynok.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Retains Moisture | Cleanses Gently | pH Balanced",
        "rating":4.8,
        "reviews":137,
        "price":"349",
        "sellerTag":"BEST SELLER",
        "category":"Bath",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


     },
     {
        "id":"B3",
        "name":"Deeply Nourishing Body Wash for babies, 400ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/b/o/body-wash_probs_ui8gwmtjnj2sahbz.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Natural Cleansers | Tear-Free Formula",
        "rating":4.8,
        "reviews":50,
        "price":"399",
        "sellerTag":"BEST SELLER",
        "category":"Bath",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


     },
     {
        "id":"B4",
        "name":"Milky Soft Shampoo with Oats, Milk and Calendula for Babies - 400 ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/m/i/milky-soft-shampoo-1_1.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Gently Cleanses Hair | Balances Scalp pH",
        "rating":4.8,
        "reviews":22,
        "price":"399",
        "sellerTag":"MUST TRY",
        "category":"shampoo",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


     },
     {
        "id":"B5",
        "name":"Nourishing Hair Oil for Babies with Almond and Avocado Oil - 200 ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/b/a/baby_hair_oil_200_ml_1200x1200__yh1i6qtlgyc253s5.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Treats Dry Scalp | Stimulates New Hair Growth",
        "rating":5.0,
        "reviews":52,
        "price":"399",
        "sellerTag":"BEST SELLER",
        "category":"oil",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


     },
     {
        "id":"B6",
        "name":"Milky Soft Body Lotion for Babies with Oats, Milk and Calendula - 400ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/_/m/_milky-soft-body-lotion__1.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Deeply Nourishes Skin | 24-Hour Moisturization",
        "rating":4.8,
        "reviews":54,
        "price":"399",
        "sellerTag":"BEST SELLER",
        "category":"Lotion",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

     },
     {
        "id":"B7",
        "name":"Original Orange Body Lotion For Kids With Orange & Shea Butter - 400 ml (Pack of 2)",
        "pImg":"https://honasa-mamaearth-production.imgix.net/o/r/original-orange-body-lotion.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Gently Nourishes Skin | Makes Skin Soft & Supple",
        "rating":5.0,
        "reviews":1,
        "price":"798",
        "sellerTag":"BEST SELLER",
        "category":"Lotion",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


     },

     {
        "id":"B8",
        "name":"Major Mango Body Wash For Kids with Mango & Oat Protein - 300 ml (Pack of 2)",
        "pImg":"https://honasa-mamaearth-production.imgix.net/m/a/mango-body-wash.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Gently Cleanses | Sulfate-Free | Keeps Skin Soft",
        "rating":5.0,
        "reviews":1,
        "price":"798",
        "sellerTag":"BEST SELLER",
        "category":"Bath",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


     },
     {
        "id":"B9",
        "name":"Gentle Cleansing Shampoo, 400ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/s/h/shampo_props_ky0ozlvydza60eyc.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Natural Cleansers | Tear-Free Formula",
        "rating":4.8,
        "reviews":22,
        "price":"399",
        "sellerTag":"MUST TRY",
        "category":"shampoo",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

     },

     {
        "id":"B10",
        "name":"Deeply Nourishing Body Wash for Babies 400ml and Gentle Cleansing Shampoo 400ml Combo",
        "pImg":"https://honasa-mamaearth-production.imgix.net/b/a/baby_wash_shampoo_400ml__1_1_hwl1d0hyj5mzwzsz.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Natural Cleansers | Tear-Free Formula",
        "rating":4.8,
        "reviews":22,
        "price":"798",
        "sellerTag":"MUST TRY",
        "category":"shampoo",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

     },
     
     {
        "id":"B11",
        "name":"Soothing Massage Oil for Babies with Sesame, Almond and Jojoba Oil - 200ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/b/a/baby_massage_oil_200_ml__1200x1200__i0oy2adtieurwcls.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Sesame Power | Mild & Safe | Light Oil",
        "rating":5.0,
        "reviews":52,
        "price":"399",
        "sellerTag":"BEST SELLER",
        "category":"oil",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


     },

     {
        "id":"B12",
        "name":"Welcome Baby Essential Kit",
        "pImg":"https://honasa-mamaearth-production.imgix.net/w/e/welcome-baby-essential-kit_iov2mdbdmdyyv6vu.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Crafted for Gentle Care | Relieves Discomfort",
        "rating":5.0,
        "reviews":52,
        "price":"1743",
        "sellerTag":"BEST SELLER",
        "category":"oil",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


     },


]

export const Babybest = [
    
   {
      "id":"B13",
      "name":"Milky Soft Face Cream With Murumuru Butter for Babies, 60 ml",
      "pImg":"https://honasa-mamaearth-production.imgix.net/_/m/_milky_soft_face_cream_.jpg?auto=compress&fit=scale&w=400&h=400",
      "pShortDec":"Moisturizes | Soothes | Heals Chapped Skin",
      "rating":4.9,
      "reviews":217,
      "price":"199",
      "sellerTag":"BEST SELLER",
      "category":"Lotion",
      "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
      "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
      "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
      "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
      "pImg4":"",
      "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
      "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
      "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
      "dtitle1":"Natural Cleansers",
      "dtitle2":"Tear-Free Formula",
      "dtitle3":"Nourishes The Body",
      "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
      "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
      "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


   },
   {
      "id":"B14",
      "name":"Moisturizing Bathing Bar Soap For Babies, pack of 2*75g",
      "pImg":"https://honasa-mamaearth-production.imgix.net/f/d/fds_9573-props_qwhqvlzshodrynok.jpg?auto=compress&fit=scale&w=400&h=400",
      "pShortDec":"Retains Moisture | Cleanses Gently | pH Balanced",
      "rating":4.8,
      "reviews":137,
      "price":"349",
      "sellerTag":"BEST SELLER",
      "category":"Bath",
      "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
      "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
      "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
      "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
      "pImg4":"",
      "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
      "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
      "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
      "dtitle1":"Natural Cleansers",
      "dtitle2":"Tear-Free Formula",
      "dtitle3":"Nourishes The Body",
      "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
      "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
      "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


   },
   {
      "id":"B15",
      "name":"Deeply Nourishing Body Wash for babies, 400ml",
      "pImg":"https://honasa-mamaearth-production.imgix.net/b/o/body-wash_probs_ui8gwmtjnj2sahbz.jpg?auto=compress&fit=scale&w=400&h=400",
      "pShortDec":"Natural Cleansers | Tear-Free Formula",
      "rating":4.8,
      "reviews":50,
      "price":"399",
      "sellerTag":"BEST SELLER",
      "category":"Bath",
      "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
      "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
      "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
      "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
      "pImg4":"",
      "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
      "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
      "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
      "dtitle1":"Natural Cleansers",
      "dtitle2":"Tear-Free Formula",
      "dtitle3":"Nourishes The Body",
      "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
      "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
      "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


   },
   {
      "id":"B16",
      "name":"Milky Soft Shampoo with Oats, Milk and Calendula for Babies - 400 ml",
      "pImg":"https://honasa-mamaearth-production.imgix.net/m/i/milky-soft-shampoo-1_1.jpg?auto=compress&fit=scale&w=400&h=400",
      "pShortDec":"Gently Cleanses Hair | Balances Scalp pH",
      "rating":4.8,
      "reviews":22,
      "price":"399",
      "sellerTag":"MUST TRY",
      "category":"shampoo",
      "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
      "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
      "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
      "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
      "pImg4":"",
      "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
      "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
      "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
      "dtitle1":"Natural Cleansers",
      "dtitle2":"Tear-Free Formula",
      "dtitle3":"Nourishes The Body",
      "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
      "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
      "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


   },
   {
      "id":"B17",
      "name":"Nourishing Hair Oil for Babies with Almond and Avocado Oil - 200 ml",
      "pImg":"https://honasa-mamaearth-production.imgix.net/b/a/baby_hair_oil_200_ml_1200x1200__yh1i6qtlgyc253s5.jpg?auto=compress&fit=scale&w=400&h=400",
      "pShortDec":"Treats Dry Scalp | Stimulates New Hair Growth",
      "rating":5.0,
      "reviews":52,
      "price":"399",
      "sellerTag":"BEST SELLER",
      "category":"oil",
      "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
      "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
      "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
      "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
      "pImg4":"",
      "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
      "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
      "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
      "dtitle1":"Natural Cleansers",
      "dtitle2":"Tear-Free Formula",
      "dtitle3":"Nourishes The Body",
      "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
      "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
      "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."


   },
   {
      "id":"B18",
      "name":"Milky Soft Body Lotion for Babies with Oats, Milk and Calendula - 400ml",
      "pImg":"https://honasa-mamaearth-production.imgix.net/_/m/_milky-soft-body-lotion__1.jpg?auto=compress&fit=scale&w=400&h=400",
      "pShortDec":"Deeply Nourishes Skin | 24-Hour Moisturization",
      "rating":4.8,
      "reviews":54,
      "price":"399",
      "sellerTag":"BEST SELLER",
      "category":"Lotion",
      "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
      "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
      "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
      "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
      "pImg4":"",
      "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
      "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
      "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
      "dtitle1":"Natural Cleansers",
      "dtitle2":"Tear-Free Formula",
      "dtitle3":"Nourishes The Body",
      "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
      "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
      "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

   }

]