export const Bodydatas = [

     {
        "id":"BD1",
        "name":"Charcoal Body Wash With Charcoal and Mint for Deep Cleansing - 300 ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/c/h/charcoal-body-wash-1_znn27t24cu3q9szq.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Deeply Cleanses | Rejuvenates & Refreshes",
        "rating":4.9,
        "reviews":66,
        "price":"299",
        "sellerTag":"",
        "category":"Body wash",
        "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

     },
     {
        "id":"BD2",
        "name":"Ubtan Body Wash With Turmeric and Saffron for Glowing Skin - 300 ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/u/b/ubtan-body-wash-1_c7usn1sqjckdbdg5.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Deeply Cleanses | Unveils Glow | Gently Exfoliates",
        "rating":4.9,
        "reviews":66,
        "price":"299",
        "sellerTag":"",
        "category":"Body wash",
        "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

     },

     {
        "id":"BD3",
        "name":"Ubtan Nourishing Bathing Soap With Turmeric and Saffron - 375g",
        "pImg":"https://honasa-mamaearth-production.imgix.net/u/b/ubtan-soap-1.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Removes Tan | 76% TFM for Extra Moisturization",
        "rating":5.0,
        "reviews":66,
        "price":"375",
        "sellerTag":"",
        "category":"Body scrub",
        "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

     },
     {
        "id":"BD4",
        "name":"Ubtan Body Care Combo",
        "pImg":"https://honasa-mamaearth-production.imgix.net/c/o/combo_1.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Deeply Cleanses | Imparts Glow | Moisturizes Skin",
        "rating":4.9,
        "reviews":66,
        "price":"698",
        "sellerTag":"",
        "category":"Body wash",
        "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

     },
     {
        "id":"BD5",
        "name":"Charcoal Body Wash With Charcoal and Mint for Deep Cleansing - 300 ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/c/h/charcoal-body-wash-1_znn27t24cu3q9szq.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Deeply Cleanses | Rejuvenates & Refreshes",
        "rating":4.9,
        "reviews":66,
        "price":"299",
        "sellerTag":"",
        "category":"Body scrub",
        "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

     },
     {
        "id":"BD6",
        "name":"Vitamin C Body Wash with Vitamin C and Honey for Skin Illumination - 300ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/v/i/vitamin-c-body-wash-1_1_53czcglrjlhrmufp.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Deeply Cleanses | Brightens Skin |Unlocks Radiance",
        "rating":4.8,
        "reviews":66,
        "price":"225",
        "sellerTag":"",
        "category":"Body Lotion",
        "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

     },
     {
        "id":"BD7",
        "name":"Tea Tree Nourishing Bathing Soap With Tea Tree and Neem for Skin Purification - 5x75g",
        "pImg":"https://honasa-mamaearth-production.imgix.net/_/t/_tea-tree-nourishing-bathing-soap_1.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Purifies Skin | 76% TFM for Extra Moisturization",
        "rating":4.8,
        "reviews":66,
        "price":"375",
        "sellerTag":"",
        "category":"Body Lotion",
        "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

     },
     {
        "id":"BD8",
        "name":"Natural Nourishing Bathing Soaps - 5x75g",
        "pImg":"https://honasa-mamaearth-production.imgix.net/a/l/all-range-1.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Sulfate-Free | 76% TFM for Extra Moisturization",
        "rating":4.9,
        "reviews":66,
        "price":"375",
        "sellerTag":"",
        "category":"Body wash",
        "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

     },
     {
        "id":"BD9",
        "name":"CoCo Body Wash With Coffee and Cocoa For Skin Awakening - 300 ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/c/o/coco-body-wash-1_1_dc3xrp64r0jvunpp.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Gently Cleanses |Rejuvenates Skin | Awakens Senses",
        "rating":4.8,
        "reviews":66,
        "price":"299",
        "sellerTag":"",
        "category":"Body Lotion",
        "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

     },
     {
        "id":"BD10",
        "name":"Tea Tree Body Wash With Tea Tree and Neem For Skin Purification - 300 ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/t/e/tea-tree-body-wash-1_1_vzbz9azcbbuefo72.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Gently Cleanses & Detoxifies Skin | Antibacterial",
        "rating":4.9,
        "reviews":66,
        "price":"299",
        "sellerTag":"",
        "category":"Body scrub",
        "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

     },


]

export const Bodycare = [
      
   {
      "id":"BD11",
      "name":"Charcoal Body Wash With Charcoal and Mint for Deep Cleansing - 300 ml",
      "pImg":"https://honasa-mamaearth-production.imgix.net/c/h/charcoal-body-wash-1_znn27t24cu3q9szq.jpg?auto=compress&fit=scale&w=400&h=400",
      "pShortDec":"Deeply Cleanses | Rejuvenates & Refreshes",
      "rating":4.9,
      "reviews":66,
      "price":"299",
      "sellerTag":"BEST SELLER",
      "category":"Body",
       "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

   },
   {
      "id":"BD12",
      "name":"Ubtan Body Wash With Turmeric and Saffron for Glowing Skin - 300 ml",
      "pImg":"https://honasa-mamaearth-production.imgix.net/u/b/ubtan-body-wash-1_c7usn1sqjckdbdg5.jpg?auto=compress&fit=scale&w=400&h=400",
      "pShortDec":"Deeply Cleanses | Unveils Glow | Gently Exfoliates",
      "rating":4.9,
      "reviews":66,
      "price":"299",
      "sellerTag":"BEST SELLER",
      "category":"Body",
       "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

   },

   {
      "id":"BD13",
      "name":"Ubtan Nourishing Bathing Soap With Turmeric and Saffron - 375g",
      "pImg":"https://honasa-mamaearth-production.imgix.net/u/b/ubtan-soap-1.jpg?auto=compress&fit=scale&w=400&h=400",
      "pShortDec":"Removes Tan | 76% TFM for Extra Moisturization",
      "rating":5.0,
      "reviews":66,
      "price":"375",
      "sellerTag":"BEST SELLER",
      "category":"Body",
       "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

   },
   {
      "id":"BD14",
      "name":"Ubtan Body Care Combo",
      "pImg":"https://honasa-mamaearth-production.imgix.net/c/o/combo_1.jpg?auto=compress&fit=scale&w=400&h=400",
      "pShortDec":"Deeply Cleanses | Imparts Glow | Moisturizes Skin",
      "rating":4.9,
      "reviews":66,
      "price":"698",
      "sellerTag":"BEST SELLER",
      "category":"Body",
       "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

   },
   {
      "id":"BD15",
      "name":"Charcoal Body Wash With Charcoal and Mint for Deep Cleansing - 300 ml",
      "pImg":"https://honasa-mamaearth-production.imgix.net/c/h/charcoal-body-wash-1_znn27t24cu3q9szq.jpg?auto=compress&fit=scale&w=400&h=400",
      "pShortDec":"Deeply Cleanses | Rejuvenates & Refreshes",
      "rating":4.9,
      "reviews":66,
      "price":"299",
      "sellerTag":"",
      "category":"Body",
       "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

   },
   {
      "id":"BD16",
      "name":"Vitamin C Body Wash with Vitamin C and Honey for Skin Illumination - 300ml",
      "pImg":"https://honasa-mamaearth-production.imgix.net/v/i/vitamin-c-body-wash-1_1_53czcglrjlhrmufp.jpg?auto=compress&fit=scale&w=400&h=400",
      "pShortDec":"Deeply Cleanses | Brightens Skin |Unlocks Radiance",
      "rating":4.8,
      "reviews":66,
      "price":"225",
      "sellerTag":"",
      "category":"Body",
       "description":"Finally, a shampoo you can commit to. Our BhringAmla Shampoo is a serious multitasker. This Ayurvedic blend of Bhringraj, Amla, and many other herbs reduces hair fall, repairs damaged hair, and reduces dandruff.Crafted with time-tested natural ingredients such as Bhringraj and Amla, the shampoo has oil that has been made following the traditional ‘Kshirpak Vidhi.’ This is an ancient and esoteric Ayurveda process, where ‘Kshira’ or milk is combined with different herbs in a process that requires patience and precision.",
        "pImg1":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg2":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_4.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg3":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_3.jpg?auto=format&fit=crop&w=640&auto=compress",
        "pImg4":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_2.jpg?auto=format&fit=crop&w=640&auto=compress",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Dry_Scalp.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Promotes_Hair_Growth_FBAoiRU.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/Reduces_Dandruff__Soothes_Dry_Scalp.jpg",
        "dtitle1":"Repairs Damaged Hair",
        "dtitle2":"Promotes Hair Growth",
        "dtitle3":"Reduces Dandruff & Soothes Dry Scalp",
        "dDec1":"With the goodness of Ayurvedic herbs and natural oils, BhringAmla Shampoo effectively works to repair hair damage. Amla and Bhringraj make the hair healthier and stronger from root to tip.",
        "dDec2":"When you have a hair care recipe that’s 4000 years old, you can expect exceptional results. The oils present in the shampoo penetrate deep within the roots and stimulate the hair follicles, leading to increased hair growth.",
        "dDec3":"The time-tested Ayurvedic ingredients present in the shampoo ensure that the scalp is cleansed thoroughly and the roots are strengthened, leading to reduced dandruff."

   }
]