export const Hairdatas = [

    {
        "id":81,
        "name":"Onion Hair Oil for Hair Regrowth and Hair Fall Control with Redensyl, 150ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/o/n/onion-hair-shampoo-250ml-with-ingredient_2.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Boosts Hair Growth | Adds Strengths & Shine",
        "rating":4.8,
        "reviews":79,
        "price":399,
        "sellerTag":"BEST SELLER",
        "category":"Hair oil",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."
     },
     
     {
        "id":82,
        "name":"Onion Shampoo with Onion and Plant Keratin for Hair Fall Control - 250ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/o/n/onion-hair-shampoo-250ml-with-ingredient_2.jpg?auto=compress&fit=scale&w=200&h=200",
        "pShortDec":"Reduces Hair Fall | Strengthens Hair | SoftensHair",
        "rating":4.7,
        "reviews":549,
        "price":"349",
        "sellerTag":"BEST SELLER",
        "category":"Hair shampoo",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

     },

     {
        "id":83,
        "name":"Onion Hair Oil for Hair Regrowth and Hair Fall Control, 250",
        "pImg":"https://honasa-mamaearth-production.imgix.net/_/o/_onion-oil-250ml__1.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Boosts Hair Growth | Adds Strength & Shine",
        "rating":4.8,
        "reviews":429,
        "price":"599",
        "sellerTag":"BEST SELLER",
        "category":"Hair oil",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."
     },

     {
        "id":84,
        "name":"Onion Conditioner for Hair Fall Control-250ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/o/n/onion-hair-conditioner-250ml-with-ingredient_2.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Reduces Hair Fall | Detangles Hair | Softens Hair",
        "rating":4.7,
        "reviews":87,
        "price":"349",
        "sellerTag":"MUST TRY",
        "category":"Hair conditioner",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

     },
     
     {
        "id":85,
        "name":"Onion Shampoo with Onion and Plant Keratin for Hair Fall Control - 400ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/o/n/onion-hair-shampoo-250ml-with-ingredient_2.jpg?auto=compress&fit=scale&w=200&h=200",
        "pShortDec":"Reduces Hair Fall | Strengthens Hair | SoftensHair",
        "rating":4.9,
        "reviews":199,
        "price":"499",
        "sellerTag":"BEST SELLER",
        "category":"Hair shampoo",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

     },

     {
        "id":86,
        "name":"Onion Hair Serum With Onion and Biotin for Strong, Frizz-Free Hair - 100ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/o/n/onion-hair-serum1200x1200_ad8hgvjdve7vcczs.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Reduces Frizz & Tangles | Minimizes Hair Breakage",
        "rating":4.8,
        "reviews":107,
        "price":"299",
        "sellerTag":"MUST TRY",
        "category":"Hair serum",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."
     },
     
     {
        "id":87,
        "name":"Onion Hair Oil for Hair Regrowth and Hair Fall Control,250ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/_/o/_onion-oil-250ml__1.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Boosts Hair Growth | Adds Strengths & Shine",
        "rating":4.8,
        "reviews":429,
        "price":599,
        "sellerTag":"BEST SELLER",
        "category":"Hair oil",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."
     },

     {
        "id":88,
        "name":"Onion Conditioner for Hair Fall Control - 250ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/o/n/onion-hair-conditioner-250ml-with-ingredient_2.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Reduces Hair Fall | Detangles Hair | Softens Hair",
        "rating":4.7,
        "reviews":87,
        "price":349,
        "sellerTag":"BEST SELLER",
        "category":"Hair conditioner",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

     },

     {
        "id":89,
        "name":"BhringAmla Shampoo with Bhringraj and Amla for Intense Hair Treatment - 250",
        "pImg":"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_shampoo_1.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Repairs Damaged Hair | Boosts Hair Growth",
        "rating":4.7,
        "reviews":109,
        "price":"349",
        "sellerTag":"BEST SELLER",
        "category":"Hair shampoo",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

     },

     {
        "id":90,
        "name":"Rice Water Shampoo For Damage Repair - 250ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/r/i/rice-shampoo-with-ingredient_1_1_.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Repairs Damaged Hair | Reduces Split Ends",
        "rating":4.8,
        "reviews":137,
        "price":"349",
        "sellerTag":"BEST SELLER",
        "category":"Hair shampoo",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

     },

     {
        "id":91,
        "name":"Onion Hair Mask, For Hair Fall Control, With Onion Oil and Organic Bamboo Vinegar, 200ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/o/n/onion_hair_mask_1.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Reduces Hair Fall | Repairs Damaged Hair",
        "rating":4.9,
        "reviews":136,
        "price":"599",
        "sellerTag":"",
        "category":"Hair mask",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

     },

     {
        "id":92,
        "name":"Onion Scalp Serum with Onion and Niacinamide for Healthy Hair Growth - 50ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/o/n/onion-scalp-serum-1.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Strengthens Hair| Reduces Hair Fall |Healthy Scalp",
        "rating":4.9,
        "reviews":83,
        "price":"599",
        "sellerTag":"MUST TRY",
        "category":"Hair serum",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

     },

     {
        "id":93,
        "name":"Rice Water Conditioner with Rice Water and Keratin for Damaged, Dry and Frizzy Hair - 250 ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/r/i/rice-conditiner-with-ingredient_1.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Reduces Split Ends | Prevents Hair Breakage",
        "rating":4.9,
        "reviews":50,
        "price":"349",
        "sellerTag":"BEST SELLER",
        "category":"Hair conditioner",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

     },
     {
        "id":94,
        "name":"Argan Hair Mask with Argan, Avocado Oil, and Milk Protein for Frizz-free and Stronger Hair-200ml",
        "pImg":"https://honasa-mamaearth-production.imgix.net/a/r/argan-hair-mask-1.jpg?auto=compress&fit=scale&w=400&h=400",
        "pShortDec":"Strengthens Hair| Reduces Frizz |Deeply Conditions",
        "rating":4.9,
        "reviews":136,
        "price":"599",
        "sellerTag":"",
        "category":"Hair mask",
        "description":"Hi! I am Mamaearth Gentle Cleansing Shampoo. I understand that shampooing is not an easy task and involves effort in real cleaning. I also understand that little ones are quite uncomfortable in getting a head bath and the shampoo has to be quick and efficient. That’s why I am here! Let your baby enjoy my thick, soft and instant foam while I gently cleanse hair and scalp. My 100% toxin-free formula gives your baby soft and nourished hair. I take special care not to irritate those sensitive eyes and be gentle on skin. I am also free from harmful chemicals like SLS, Parabens, Sulfates, and other such chemicals, ensuring a safe and happy bath time. Also, I come with MadeSafe Certificatio",
        "pImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "pImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "pImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "pImg4":"",
        "dImg1":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/015.jpg",
        "dImg2":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/016.jpg",
        "dImg3":"https://mmrth-mg-cs.honasa-production.net/pub/media/wysiwyg/017.jpg",
        "dtitle1":"Natural Cleansers",
        "dtitle2":"Tear-Free Formula",
        "dtitle3":"Nourishes The Body",
        "dDec1":"Aloe Vera Extract moisturizes and nourishes baby’s delicate scalp skin.",
        "dDec2":"It is Tear-free, gentle yet efficient, with a 5.6 pH level – best suited for baby skin.",
        "dDec3":"It is enriched with the goodness of Coconut-based cleansers and Jojoba Oil. They help nourish the skin and increase its moisture content."

     },


]